// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Transaction struct {
	ID              string           `json:"id"`
	TransactionType *TransactionType `json:"transactionType"`
	Value           int32            `json:"value"`
	Date            string           `json:"date"`
	User            *User            `json:"user"`
}

type TransactionFilter struct {
	ID                *string `json:"id,omitempty"`
	UserID            *string `json:"userId,omitempty"`
	TransactionTypeID *string `json:"transactionTypeId,omitempty"`
	Date              *string `json:"date,omitempty"`
	MinValue          *int32  `json:"minValue,omitempty"`
	MaxValue          *int32  `json:"maxValue,omitempty"`
}

type TransactionInput struct {
	TransactionTypeID string `json:"transactionTypeId"`
	UserID            string `json:"userId"`
	Value             int32  `json:"value"`
	Date              string `json:"date"`
}

type TransactionType struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Description  *string        `json:"description,omitempty"`
	Transactions []*Transaction `json:"transactions"`
}

type TransactionTypeInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type User struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Cnpj         string         `json:"cnpj"`
	Transactions []*Transaction `json:"transactions"`
}

type UserInput struct {
	Name string `json:"name"`
	Cnpj string `json:"cnpj"`
}
